*** Settings ***
Resource    navigateur.resource
Resource    pages/page_connexion.resource
Resource    pages/page_inscription.resource
Resource    pages/page_mot_de_passe_oublie.resource
Resource    pages/page_reservation.resource
Resource    pages/page_reservations_voyageur.resource
Resource    pages/page_reservation_parcours.resource
Resource    pages/page_hote.resource
Resource    pages/page_annonce.resource
Resource    pages/page_annonce_parcours.resource